[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.10.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
pm-acp = { path = "crates/pm-acp" }
pm-core = { path = "crates/pm-core" }
pm-dap = { path = "crates/pm-dap" }
pm-gfx = { path = "crates/pm-gfx" }
pm-text = { path = "crates/pm-text" }
pm-ui = { path = "crates/pm-ui" }
pm-vim = { path = "crates/pm-vim" }
pm-vt = { path = "crates/pm-vt" }

[profile.dist]
inherits = "release"
lto = "thin"
codegen-units = 1
strip = true

[profile.dev.package."*"]
opt-level = 3
