[package]
name = "pandemonium"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
pm-acp.workspace = true
pm-core.workspace = true
pm-gfx.workspace = true
pm-text.workspace = true
pm-ui.workspace = true
pm-vim.workspace = true
pm-vt.workspace = true
rfd = { version = "0.17.2", default-features = false, features = ["xdg-portal"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_norway = "0.9.42"
winit = "0.30.13"
